In [10]:
from sklearn.datasets import load_iris
import pandas as pd
import func.calculate as calc
iris = load_iris()
X =pd.DataFrame(iris.data, columns=iris.feature_names)

In [2]:
k=3

In [3]:
class Kmeans:
    def __init__(self,k):
        self.k=k
        self.data=None
        self.center=None

    def fit(self,data,epochs,inplace=False):
        if inplace:
            self.data=data
        else:
            self.data=pd.DataFrame(data)
        if self.center:
            chosen_data=self.center
        else:
            chosen_data=data.sample(self.k)
        distance=pd.DataFrame()
        for epoch in range(epochs):
            for i in range(chosen_data.shape[0]):
                distance["distance{}".format(i)]=calc.EuclideanDistance(chosen_data.iloc[i,:],self.data.iloc[:,:chosen_data.shape[1]])
            self.data["class"]=distance.idxmin(axis=1).apply(lambda x:x[-1]).astype(int)
            for i in range(chosen_data.shape[0]):
                chosen_data.iloc[i,:]=calc.cal_center(self.data.iloc[:,0:4].where(self.data["class"]==i).dropna().values)
                # print(chosen_data)
        
        self.center=chosen_data.reset_index(drop=True)
        

        return self.data
    
    def class_center(self):
        return self.center
    
    def predict(self,test):
        pass

In [4]:
from func.Classfy import Kmeans

In [5]:
X

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [6]:
model = Kmeans(3)
_=model.fit(X,100)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,1
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,1

In [7]:
_=model.predict(X)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1]

In [8]:
print(model.class_center())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           5.006000          3.428000           1.462000          0.246000
1           5.901613          2.748387           4.393548          1.433871
2           6.850000          3.073684           5.742105          2.071053

In [9]:
# center_data=chosen_data.iloc[X["class"],:].reset_index(drop=True)
# center_data.columns=["center_0","center_1","center_2","center_3"]
# X=pd.concat([X,center_data],axis=1)
# cal_center(X.iloc[:,0:4].where(X["class"]==0).dropna().values)